# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Never say die
tagline:             '永不言败'
description:         '这里什么都没有！'
url:                 https://www.neversaydie.xyz
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Brandon
  url:               https://www.neversaydie.xyz
  email:             oo-oo@outlook.com

# Custom vars
version:             1.0.0
