# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           date
#relative_permalinks: true

timezone:            Asia/Shanghai

# Setup
title:               Never say die
tagline:             '永不言败'
description:         'Never say die'
url:                 https://www.neversaydie.xyz
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Brandon
  url:               https://www.neversaydie.xyz
  email:             oo-oo@outlook.com

# Custom vars
version:             1.0.0
